### ISSUE TITLE
macOS builds should not depend on clock_gettime

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/distribution-scripts#14]
`clock_gettime` doesn't exist on macOS versions previous to Sierra (10.12).

Crystal's codebase [explicitly tries to avoid it](https://github.com/crystal-lang/crystal/blob/f3168b6be999dc10e7b63fa2281e7d9265087609/src/crystal/system/unix/time.cr#L5-L10), but [the builds done by the CI](https://8387-6887813-gh.circle-artifacts.com/0/dist_packages/crystal-0.25.1-1-darwin-x86_64.tar.gz) still [depend on it](https://gist.github.com/matiasgarciaisaia/e612199d8112872a035d0f411821ec28), failing to run on OS X El Capitan (10.11).

Local builds (even in Sierra) don't depend on them, so there must be something odd in the omnibus script or something.

See Homebrew/homebrew-core#29527

**Comment by matiasgarciaisaia** [comment]
On Homebrew/homebrew-core#29527 [(comment)](https://github.com/Homebrew/homebrew-core/pull/29527#issuecomment-401492601), @Sija asked:
> @matiasgarciaisaia Shouldn't [0.25.1 release files](https://github.com/crystal-lang/crystal/releases/tag/0.25.1) for macOS be updated as well?

They will, but we haven't built them yet. And, given the issues you're facing, we may probably have to fix _something else_ before closing this as solved.

**Comment by bcardiff** [comment]
Fixed by #15 .
Both 0.25.0-2 and 0.25.1-2 are built to work with 10.11 and published in github releases.
