### ISSUE TITLE
Include libxml2-static and xz-static in the Docker image

### ISSUE THREAD

**Issue by vitobotta** [crystal-lang/distribution-scripts#241]
Hi! I was having problems compiling a project using the latest Alpine image, and installing libxml2-static and xz-static helped. Could these be included in the Docker image? I think they are commonly used by many projects. Thanks!

**Comment by straight-shoota** [comment]
Yeah, the static libs should be included. I think they were originally contained in the `*-dev` packages but split into separate `*-static` packages at some point.
