### ISSUE TITLE
Debian 12 (Bookworm) not present in OBS builds

### ISSUE THREAD

**Issue by markozajc** [crystal-lang/distribution-scripts#257]
(apologies in advance if this is not the right repository to open the issue in)
It seems that the [OBS repository](https://download.opensuse.org/repositories/devel:/languages:/crystal/) has a Bookworm-sized gap between Debian 11 and testing (which I assume tracks 13/Trixie). While using the Debian_Testing version still seems to work on Debian 12, it could stop working anytime. Please add Debian 12 to the version list.

**Comment by straight-shoota** [comment]
I have enabled the Debian 12 repository in OBS. Package is building and should appear shortly.

**Comment by markozajc** [comment]
Fixed, thanks!
