### ISSUE TITLE
Vagrant box

### ISSUE THREAD

**Issue by duraki** [crystal-lang/distribution-scripts#32]
There is official box provision located at [vagrantup](https://app.vagrantup.com/manastech/boxes/crystal), but the last update is quite far from what we have right now.
  
As development on **Docker for MacOS** is barely usable, some of us would appreciate an update to above box with latest `crystal-lang` releases.
  
Thanks!

**Comment by bcardiff** [comment]
Hi @duraki the vagrant box was/is not intended as a release channel.

I use docker for macOS on crystal, can we discuss some of the issues you are having in https://forum.crystal-lang.org ?

If you are used to working with vagrant, having a Vagrantfile with the supported distro of your choice should be straight forward following the installations instructions at https://crystal-lang.org/reference/installation/ 

So far there was no interest in having a crystal vagrant box so I would encourage one of the two options mentioned above for the time being.

**Comment by duraki** [comment]
Thank you. I will reference to the Crystal forum.
