### ISSUE TITLE
Uninstalling rpm package does not clear directories

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/distribution-scripts#34]
It seems we need to use `--auto-add-directories` or `--directories` to the fpm call to build rpm (64 and 32 bits) in https://github.com/crystal-lang/distribution-scripts/blob/master/linux/Makefile

Extracted from https://github.com/crystal-lang/crystal/issues/7421

**Comment by straight-shoota** [comment]
Resolved by #132
