### ISSUE TITLE
Snapcraft support `armhf` architecture?

### ISSUE THREAD

**Issue by drujensen** [crystal-lang/distribution-scripts#40]
Kudos for adding snapcraft support. 🎉 👏 

Any chance `armhf` architecture will be supported?
```
$sudo snap install crystal
error: snap "crystal" is not available on stable for this architecture (armhf)
       but exists on other architectures (amd64).
```

**Comment by ysbaddaden** [comment]
I'm not sure. We have a soft/hard float issue on arm32 that we haven't been able to fix :(

Support for AArch64 (arm64) is much better.

**Comment by Blacksmoke16** [comment]
What about any of the other architectures snap supports?  I see there is a `i386` binary on the latest Crystal release.

**Comment by drujensen** [comment]
I tried to build crystal 0.27.0 on a raspberry pi 4 (raspian buster) and ran into INT64 issues.  Crystal doesn't seem to support 32bit OS'es anymore. I think I will byte the bullet and move to an arm64 OS.

Hoping to see `arm64` support in snapcraft soon.
