### ISSUE TITLE
Provide newer Git version in the Docker image

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/distribution-scripts#61]
The current version (which I guess is [2.17.1 from Bionic](https://packages.ubuntu.com/bionic-updates/git)) causes GitHub Actions to not actually expose the Git repo as a repo but just check out the bare files, which can be a hard-to-debug surprise when people rely on the image in GitHub Actions.

> The repository will be downloaded using the GitHub REST API
> To create a local Git repository instead, add Git 2.18 or higher to the PATH

https://github.com/crystal-lang/crystal/runs/597246816?check_suite_focus=true#step:3:20

---

I've had to work around this by not using the image and instead installing Crystal with something like `snap`

**Comment by straight-shoota** [comment]
I'd simply wait for Ubuntu 20.04 LTS which should be available in about two weaks.
